# Generated by Django 3.1.1 on 2020-09-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome do cliente: ')),
                ('usuario', models.CharField(max_length=15, verbose_name='Usuario: ')),
                ('senha', models.CharField(max_length=15, verbose_name='Senha: ')),
            ],
        ),
    ]
