# Generated by Django 3.1.1 on 2020-09-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(max_length=15, unique=True, verbose_name='Usuario: '),
        ),
    ]
