# Generated by Django 3.1.1 on 2020-10-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_site', '0002_auto_20200918_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flintstone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome do Flintstone: ')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade do Flintstone:  ')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=40, verbose_name='Nome: '),
        ),
    ]
